import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/match.dart';
import '../models/match_event.dart';
import '../models/poll.dart';
import '../services/api_client.dart';
import '../services/socket_client.dart';

class MatchRoomState {
  final Match? match;
  final List<MatchEvent> events;
  final List<Poll> polls;
  final Map<String, int> reactionCounts; // "<eventId>:<emoji>" → count
  final bool connected;
  final int homeScore;
  final int awayScore;
  final String? error;

  const MatchRoomState({
    this.match,
    this.events = const [],
    this.polls = const [],
    this.reactionCounts = const {},
    this.connected = false,
    this.homeScore = 0,
    this.awayScore = 0,
    this.error,
  });

  MatchRoomState copyWith({
    Match? match,
    List<MatchEvent>? events,
    List<Poll>? polls,
    Map<String, int>? reactionCounts,
    bool? connected,
    int? homeScore,
    int? awayScore,
    String? error,
  }) {
    return MatchRoomState(
      match: match ?? this.match,
      events: events ?? this.events,
      polls: polls ?? this.polls,
      reactionCounts: reactionCounts ?? this.reactionCounts,
      connected: connected ?? this.connected,
      homeScore: homeScore ?? this.homeScore,
      awayScore: awayScore ?? this.awayScore,
      error: error,
    );
  }
}

class MatchRoomController extends StateNotifier<MatchRoomState> {
  MatchRoomController(this._api, this._factory, this.matchId)
    : super(const MatchRoomState()) {
    _init();
  }

  final ApiClient _api;
  final MatchSocketFactory _factory;
  final int matchId;
  MatchSocket? _socket;

  Future<void> _init() async {
    try {
      final match = await _api.getMatch(matchId);
      final events = await _api.getMatchEvents(matchId);
      final polls = await _api.polls(matchId: matchId);
      state = state.copyWith(
        match: match,
        events: events.reversed.toList(),
        polls: polls,
        homeScore: match.homeScore,
        awayScore: match.awayScore,
      );
      await _openSocket();
    } catch (e) {
      state = state.copyWith(error: e.toString());
    }
  }

  Future<void> _openSocket() async {
    _socket = await _factory.create();
    if (_socket == null) {
      state = state.copyWith(error: 'not authenticated');
      return;
    }
    await _socket!.connect(matchId);
    state = state.copyWith(connected: true);
    _socket!.stream.listen(
      _onMessage,
      onError: (e) {
        state = state.copyWith(connected: false, error: e.toString());
      },
    );
  }

  void _onMessage(Map<String, dynamic> m) {
    final t = m['type'] as String?;
    switch (t) {
      case 'match.event':
        final ev = MatchEvent.fromWsPayload(m);
        state = state.copyWith(events: [ev, ...state.events]);
        break;
      case 'match.score':
        state = state.copyWith(
          homeScore: (m['home'] ?? state.homeScore) as int,
          awayScore: (m['away'] ?? state.awayScore) as int,
        );
        break;
      case 'match.reaction':
        final key = '${m['target_id']}:${m['emoji']}';
        final next = Map<String, int>.from(state.reactionCounts);
        next[key] = (m['count'] ?? 0) as int;
        state = state.copyWith(reactionCounts: next);
        break;
      case 'match.poll.open':
        final poll = Poll(
          id: m['id'] as int,
          matchId: matchId,
          question: m['question'] as String,
          options: ((m['options'] ?? []) as List)
              .map((e) => e as String)
              .toList(),
          counts: List<int>.filled(((m['options'] ?? []) as List).length, 0),
          myVote: null,
          closesAt: m['closes_at'] == null
              ? null
              : DateTime.tryParse(m['closes_at']),
          autoGenerated: true,
        );
        state = state.copyWith(polls: [poll, ...state.polls]);
        break;
      case 'match.poll.update':
        final id = m['id'] as int;
        final counts = ((m['counts'] ?? []) as List)
            .map((e) => e as int)
            .toList();
        final updated = state.polls.map((p) {
          if (p.id != id) return p;
          return Poll(
            id: p.id,
            matchId: p.matchId,
            question: p.question,
            options: p.options,
            counts: counts,
            myVote: p.myVote,
            closesAt: p.closesAt,
            autoGenerated: p.autoGenerated,
          );
        }).toList();
        state = state.copyWith(polls: updated);
        break;
      case 'match.welcome':
      case 'pong':
        // server hello / heartbeat — no-op
        break;
      default:
        if (kDebugMode) debugPrint('match WS unknown: $m');
    }
  }

  void react({required int eventId, required String emoji}) {
    _socket?.sendReaction(
      targetType: 'MATCH_EVENT',
      targetId: eventId,
      emoji: emoji,
    );
  }

  void votePoll(int pollId, int optionIndex) {
    _socket?.votePoll(pollId, optionIndex);
  }

  @override
  void dispose() {
    _socket?.dispose();
    super.dispose();
  }
}

final matchRoomProvider = StateNotifierProvider.autoDispose
    .family<MatchRoomController, MatchRoomState, int>((ref, matchId) {
      return MatchRoomController(
        ref.read(apiClientProvider),
        ref.read(matchSocketFactoryProvider),
        matchId,
      );
    });
