class Poll {
  final int id;
  final int? matchId;
  final String question;
  final List<String> options;
  final List<int> counts;
  final int? myVote;
  final DateTime? closesAt;
  final bool autoGenerated;

  Poll({
    required this.id,
    required this.matchId,
    required this.question,
    required this.options,
    required this.counts,
    required this.myVote,
    required this.closesAt,
    required this.autoGenerated,
  });

  int get total => counts.fold(0, (a, b) => a + b);

  factory Poll.fromJson(Map<String, dynamic> j) => Poll(
    id: j['id'] as int,
    matchId: j['match'] as int?,
    question: j['question'] as String,
    options: ((j['options'] ?? []) as List).map((e) => e as String).toList(),
    counts: ((j['counts'] ?? []) as List).map((e) => e as int).toList(),
    myVote: j['my_vote'] as int?,
    closesAt: j['closes_at'] == null
        ? null
        : DateTime.tryParse(j['closes_at'] as String),
    autoGenerated: (j['auto_generated'] ?? false) as bool,
  );
}
