import 'package:flutter/material.dart';

import '../models/poll.dart';

class PollCard extends StatelessWidget {
  const PollCard({super.key, required this.poll, required this.onVote});
  final Poll poll;
  final void Function(int optionIndex) onVote;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 280,
      margin: const EdgeInsets.symmetric(vertical: 6, horizontal: 6),
      child: Card(
        elevation: 1,
        child: Padding(
          padding: const EdgeInsets.all(10),
          // Scrollable so polls with many options don't overflow the
          // horizontal carousel's fixed height.
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                Row(
                  children: [
                    const Icon(Icons.poll_outlined, size: 16),
                    const SizedBox(width: 6),
                    if (poll.autoGenerated)
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 6, vertical: 2),
                        decoration: BoxDecoration(
                          color: Theme.of(context).colorScheme.primaryContainer,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: const Text('AUTO',
                            style: TextStyle(
                                fontSize: 9, fontWeight: FontWeight.w800)),
                      ),
                  ],
                ),
                const SizedBox(height: 4),
                Text(poll.question,
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                    style: const TextStyle(
                        fontWeight: FontWeight.w700, fontSize: 13)),
                const SizedBox(height: 6),
                for (int i = 0; i < poll.options.length; i++)
                  _option(context, i),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _option(BuildContext context, int i) {
    final total = poll.total;
    final c = i < poll.counts.length ? poll.counts[i] : 0;
    final pct = total == 0 ? 0.0 : c / total;
    final mine = poll.myVote == i;
    return Padding(
      padding: const EdgeInsets.only(bottom: 3),
      child: InkWell(
        onTap: () => onVote(i),
        borderRadius: BorderRadius.circular(6),
        child: SizedBox(
          height: 22,
          child: Stack(
            children: [
              Container(
                decoration: BoxDecoration(
                  color: Theme.of(context).colorScheme.surfaceContainerHighest,
                  borderRadius: BorderRadius.circular(6),
                ),
              ),
              FractionallySizedBox(
                widthFactor: pct,
                child: Container(
                  decoration: BoxDecoration(
                    color: Theme.of(context).colorScheme.primary
                        .withValues(alpha: 0.3),
                    borderRadius: BorderRadius.circular(6),
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 8),
                child: Row(
                  children: [
                    if (mine)
                      const Icon(Icons.check, size: 12)
                    else
                      const SizedBox(width: 12),
                    const SizedBox(width: 4),
                    Expanded(
                        child: Text(poll.options[i],
                            style: const TextStyle(fontSize: 11),
                            overflow: TextOverflow.ellipsis)),
                    Text('$c', style: const TextStyle(fontSize: 10)),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
